### PR TITLE
Check for duplicate symbols

### PR DESCRIPTION
**Pull request by FrederoxDev**
Changes: I have added a section of code to skip any duplicate symbol names
Motivation: Duplicate symbol's were causing my build to fail without any actual indication on why. Should be a good quality of life change to help debug stupid mistakes

Before:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:/Program Files/NASM/nasm.exe" -o "Example.dir\Release\initasm.obj" -fwin64 -I"C:\Users\blake\AppData\Roaming\Zenova\dev\inc\\" -I"C:\Users\blake\Desktop\Template-master\inc\\" -I"C:\Users\blake\Desktop\Template-master\src\\" -D"WIN32" -D"_WINDOWS" -D"NDEBUG" -D"CMAKE_INTDIR="Release"" -D"Example_EXPORTS"  "C:\Users\blake\Desktop\Template-master\src\generated\initasm.asm"" exited with code 1.	Example	C:\Program Files\CMake\share\cmake-3.26\Templates\MSBuild\nasm.targets	33	
```

After:
```
1>Found duplicate symbol: ?registerDimensionTypes@VanillaDimensionFactory@@YAXAEAV?$Factory@VDimension@@AEAVLevel@@AEAVScheduler@@@@@Z
```

### CODE REVIEW

**Comment by ThePixelGamer** [comment]
This looks solid but if possible can this functionality be extended to vtables and their entries?

**Comment by FrederoxDev** [comment]
Sure! I'll look into doing it tomorrow

**Comment by FrederoxDev** [comment]
I think its only checking for variables I needed to do, LMK if I missed anything

**Comment by ThePixelGamer** [comment]
I was also suggesting adding the same checks for vtable entries to ensure there's no duplicate functions there but I'm good to merge.

**Pull request merged**
